# Generated by Django 4.1.2 on 2022-11-30 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 15, 46, 13, 263686)),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='Male', max_length=30),
        ),
    ]
