# Generated by Django 4.1.2 on 2022-11-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_person_delete_moviedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'comorbidity',
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='personID',
            new_name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='person',
            name='comorbidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.comorbidity'),
        ),
    ]
