# Generated by Django 4.1.2 on 2022-11-29 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_journalentry_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 16, 4, 1, 861943)),
        ),
    ]
