# Generated by Django 4.1.2 on 2022-11-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_comorbidity_rename_personid_person_id_person_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='personID',
        ),
    ]
