# Generated by Django 4.1.2 on 2022-11-29 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_journalentry_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('default_quantity', models.IntegerField()),
                ('units', models.CharField(max_length=50)),
                ('potassium', models.IntegerField()),
                ('phosphorus', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('calcium', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('sugar', models.IntegerField()),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 16, 29, 46, 709626)),
        ),
    ]
