# Generated by Django 4.1.2 on 2022-11-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_id_person_personid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comorbidity',
            name='id',
        ),
        migrations.AddField(
            model_name='comorbidity',
            name='comorbidityID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
