# Generated by Django 4.1.2 on 2022-11-30 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_journalentry_date_recorded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='date_time_eaten',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date_recorded',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 30, 16, 57, 31, 668546)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='time_recorded',
            field=models.TimeField(blank=True, default='16:57:31'),
        ),
    ]
