# Generated by Django 4.1.2 on 2022-11-29 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_food_alter_journalentry_date_time_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='default_quantity',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='phosphorus',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 16, 33, 33, 890758)),
        ),
    ]
