# Generated by Django 4.1.2 on 2022-12-01 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_journalentry_date_time_eaten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_recorded',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 30, 20, 13, 22, 26860)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='time_recorded',
            field=models.TimeField(blank=True, default='20:13:22'),
        ),
    ]
