# Generated by Django 4.1.2 on 2022-11-30 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_food_default_quantity_remove_food_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 21, 12, 4, 24234)),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 21, 12, 4, 24234)),
        ),
    ]
