# Generated by Django 4.1.2 on 2022-11-30 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_journalentry_date_time_recorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_time_recorded',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 21, 14, 29, 877880)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 11, 29, 21, 14, 29, 877880)),
        ),
    ]
