# Generated by Django 4.1.2 on 2022-12-01 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_journalentry_date_recorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_recorded',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 1, 12, 43, 26, 360124)),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='time_recorded',
            field=models.TimeField(blank=True, default='12:43:26'),
        ),
    ]
